### PR TITLE
Issue 34 : Japanese Pages - About Us

### LINKED ISSUE #32: Renovate bot seems to not work
The Renovate bot seems to not create PRs, the config extends from the recommended on one which will not work with our branch naming convention but it should still create PRs, not sure why it's not doing it at the moment

### PR DESCRIPTION
**Pull request by shrotia**
- Fixed header & footer error
- Made Fragment Modal Click handler generic

Fixes #32 

Test URLs:
- Original: https://www.sunstar-foundation.org/about-us
- Before: https://main--sunstar-foundation--hlxsites.hlx.live/about-us
- After: https://issue-34-v1--sunstar-foundation--hlxsites.hlx.live/about-us

- [x] New variations introduced in this PR

Variation Name    | Documentation
------------- | -------------
 cards (Video Modal)  | [doc-link](tbd)
columns(left-section-half-width)   | [doc-link](tbd)

### CODE REVIEW

File: blocks/cards/cards.js [hunk 1]
```diff
@@ -46,6 +46,11 @@ export default function decorate(block) {
       [...li.children].forEach(addCardChildrenClasses);
     }
 
+    if (a && block.classList.contains('video-modal') && document.querySelector('.modal-fragment') !== null) {
```
Comment (sdmcraft) [inline blocks/cards/cards.js:49]: Would the page author explicitly need to specify `video-modal` or could we automatically detect this if the block has an `a` element with `href` containing `/fragments/modals/` ? If that's possible, we can reduce a bit of authoring overhead..

Comment (shrotia) [reply blocks/cards/cards.js:49]: yes, you are right, if the authors has used URLs from "fragments/modals" folder, then it is implicit that it will open as a Modal. Let me revisit this check.

**Comment by jindaliiita** [comment]
@shrotia can we have 2 different PR's for **About Us Page** and **ja** to **jp** conversion ?

**Comment by jindaliiita** [comment]
@shrotia can we have 2 different PR's for About Us Page and **ja** to **jp** conversion ?

**Comment by jindaliiita** [comment]
For screen size around 900px
extra space is coming on right and left hand side

Screenshot 2023-12-18 at 10 34 01 AM

**Comment by jindaliiita** [comment]
I was wondering if these videos are of Youtube.
Can we have autoblocking of this which will eventually calls embed block code ?

**Comment by shrotia** [comment]
> @shrotia can we have 2 different PR's for About Us Page and **ja** to **jp** conversion ?

yes, raised separate PR: https://github.com/hlxsites/sunstar-foundation/pull/54

**Comment by shrotia** [comment]
> I was wondering if these videos are of Youtube. 

Yes, they are YouTube videos.

> Can we have autoblocking of this which will eventually calls embed block code ? 

The Modal Fragment was already part of autoblock, or did I misunderstand your question?
https://github.com/hlxsites/sunstar-foundation/blob/9f5a664e08822fe0663cad9e5b48ae127c2b8d13/scripts/scripts.js#L206

**Comment by jindaliiita** [comment]
> > I was wondering if these videos are of Youtube.
> 
> Yes, they are YouTube videos.
> 
> > Can we have autoblocking of this which will eventually calls embed block code ?
> 
> The Modal Fragment was already part of autoblock, or did I misunderstand your question?
> 
> https://github.com/hlxsites/sunstar-foundation/blob/9f5a664e08822fe0663cad9e5b48ae127c2b8d13/scripts/scripts.js#L206

Ignore my comment

File: scripts/scripts.js [hunk 2]
```diff
@@ -615,6 +615,52 @@ export async function loadScript(url, attrs = {}) {
...
+    const hasSearchParam = (target.dataset.hasSearchParam === 'true');
+
+    if (!elem || e.target.dataset.hasSearchParam) {
+      if (hasSearchParam) modalFragmentBlock.innerHTML = '';
+      const wrapper = document.createElement('div');
+      wrapper.className = 'modal-wrapper';
+      wrapper.id = modalId;
+      wrapper.dataset.url = target.dataset.url;
+
+      const modal = document.createElement('div');
```
Comment (dnbute) [inline scripts/scripts.js:635]: Nit: Could we maybe refactor this to use the new-ish `dialog` tag?
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
https://caniuse.com/?search=dialog

File: blocks/columns/columns.css [hunk 3]
```diff
@@ -168,6 +168,12 @@
   margin-left: 0;
 }
 
+.columns.left-section-half-width > div > div > div {
```
Comment (dnbute) [inline blocks/columns/columns.css:171]: I see this is used for the first block on the page, instead of adding this and using a columns block, could `hero horizontal tabs` be used?
here's an example https://main--sunstar-foundation--hlxsites.hlx.page/award

File: scripts/scripts.js (hunk 2 above)
Comment (shrotia) [reply scripts/scripts.js:635]: yes, makes sense. Logged https://github.com/hlxsites/sunstar-foundation/issues/68

File: blocks/columns/columns.css (hunk 3 above)
Comment (shrotia) [reply blocks/columns/columns.css:171]: yes, I can use that. But confusing for the author, given there are no tabs.

I feel following is better for authors to follow:
image

instead of below:

image

but I am fine changing it, if we want to avoid this new variant.

Comment (sdmcraft) [reply blocks/columns/columns.css:171]: In the spirit of less is more, I think we can reuse. Arguably `Hero Horizontal Tabs` is a misnomer and should be rename to just `Hero` at some point.

Comment (shrotia) [reply blocks/columns/columns.css:171]: sure

Comment (shrotia) [reply blocks/columns/columns.css]: Done. I have removed the variant
